### ISSUE TITLE
/ms auth add给予权限不足问题

### ISSUE THREAD

**Issue by DreamOneX** [asforest/MShell#6]
# 操作简述（用xxx代替真实qq）
1. 安装`mirai-console`，`chat command`和`MShell`，登录帐号
2. 执行`/ms auth add xxx`
3. 尝试在QQ中使用`/ms help`，**得不到回复**

# status
```java
Running MiraiConsole v2.11.0-M1, built on 2022-03-08 20:34:54.
Frontend Terminal: version 2.11.0-M1, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: MCL Addon v1.2.2, Chat Command v0.5.0, MShell v2.2.1

Object Pending Finalization Count: 0
                 committed |  init  |  used   |   max   
    Heap Memory:  72.33MB  | 16.0MB | 55.4MB  | 233.93MB
Non-Heap Memory:  77.62MB  | 7.31MB | 73.93MB |    -1   
```

# 运行mirai-console的设备信息
* 系统：`Alibaba Cloud Linux release 3 (Soaring Falcon) x86_64`
* `uname -a`: `Linux xxxxx 5.10.84-10.2.al8.x86_64 #1 SMP Thu Feb 10 15:03:09 CST 2022 x86_64 x86_64 x86_64 GNU/Linux`

# 个人猜测
* 猜想1： `/ms auth add`只添加了一个权限
* 猜想2： `MShell`的验证方式存在问题

# 完整操作过程（均用xxx代替真实QQ号）<sub>~~当然了这似乎也是个临时解决方案了~~</sub>

安装MShell和ChatCommand插件后，console可以正常使用ms指令的所有功能。
使用 `/permission add xxx console:*` 和 `/ms auth add xxx` 之后，提示成功
私聊机器人，**发现`/ms`无效**，然后我查看了`config/Console/ermissionService.yml`
文件内容如下
```yaml
grantedPermissionMap:
  '*:*':
    - console
  'com.github.asforest.mshell:*':
    - fxxx
  'console:*':
    - uxxx
```
不知道f开头是什么意思，于是改成了u开头
修改后，内容如下：
```yaml
grantedPermissionMap:
  '*:*':
    - console
  'com.github.asforest.mshell:*':
    - uxxx
  'console:*':
    - uxxx
```
重启机器人，发现可以在私聊机器人的情况下执行`/ms`
输入`/ms open`，提示`没有权限使用预设 'null'`
关闭机器人，再次修改`config/Console/ermissionService.yml`，在`'com.github.asforest.mshell:*'`下，添加`-f xxx`
修改后，内容如下：
```yaml
grantedPermissionMap:
  '*:*':
    - console
  'com.github.asforest.mshell:*':
    - uxxx
    - fxxx
  'console:*':
    - uxxx
```
重启机器人，发现可以正常使用

**Comment by asforest** [comment]
我也更新到了v2.11.0-M1 + v2.11.0-M1版本，使用MShell  v2.2.1 ( 3d963575 ) ，但无法复现这个问题。

---

对于 `猜想1`的回答：`/ms auth add` 确实只添加一个权限：`com.github.asforest.mshell:*`节点下的`f___`（下划线表示实际qq号）

拥有这个权限的人，就是管理员。而普通用户的授权是两个权限（一个`com.github.asforest.mshell:use`和一个`com.github.asforest.mshell:preset.XXX`，XXX代表实际预设名）

另外f和u前缀是含义是不同的，但在私聊环境里没有太大差别。[mirai-console文档](https://github.com/mamoe/mirai-console/blob/master/docs/Permissions.md#%E5%AD%97%E7%AC%A6%E4%B8%B2%E8%A1%A8%E7%A4%BA) 里有提到

---

对于`猜想2`暂时还无法断定是插件的问题。插件的权限验证方式并未自己实现一次，而是直接调用的Mirai-Console的权限API。

你的操作过程也没什么问题，把f替换成u实际上也不影响什么。比较奇怪的是 `输入/ms open，提示没有权限使用预设 null`，你方便贴出`config.yml`和`presets.yml`的文件内容吗？

**Comment by asforest** [comment]
另外使用/ms auth list 能看到自己的qq在管理员列表中吗？

**Comment by DreamOneX** [comment]
> 另外使用/ms auth list 能看到自己的qq在管理员列表中吗？

把f替换为u后无法看到

presets.yml
```yaml
default-preset: bash
presets:
  bash:
    shell: /bin/bash
    charset: utf-8
    workdir: ''
    env: {}
    exec: ''
    single-instance: false
    terminal-columns: 80
    terminal-rows: 24
    truncation-threshold: 2048
    batching-inteval: 300
    lastwill-capacity: 2048
```
config.yml
```yaml
session-input-prefix: ''
```

**Comment by asforest** [comment]
> 把f替换为u后无法看到

这是正常现象，代码里只会输出f不会输出u

另外配置文件没有问题

提示没有权限使用预设 'null' 这个现象还能复现吗？

**Comment by DreamOneX** [comment]
> > 把f替换为u后无法看到
> 
> 这是正常现象，代码里只会输出f不会输出u
> 
> 另外配置文件没有问题
> 
> 提示没有权限使用预设 'null' 这个现象还能复现吗？
> 
> 

无法复现

**Comment by asforest** [comment]
个人觉得可能是mirai-console的bug，毕竟这v2.11.0-M1不是正式版本，可能多多少少有些小问题什么的

另一个原因是`/ms auth add`指令我每次在调试的时候都会使用，相当于高频指令吧，如果出现问题我马上就能注意到的（这里吐槽一下mirai-console启动后立即打stop关闭会有很大概率丢失并清空`config/Console/ermissionService.yml`的内容，对开发很不友好）

如果无法复现的话，那建议等v2.11正式版出来以后，看是不是仍然有这个bug

**Comment by DreamOneX** [comment]
> 个人觉得可能是mirai-console的bug，毕竟这v2.11.0-M1不是正式版本，可能多多少少有些小问题什么的
> 
> 另一个原因是`/ms auth add`指令我每次在调试的时候都会使用，相当于高频指令吧，如果出现问题我马上就能注意到的（这里吐槽一下mirai-console启动后立即打stop关闭会有很大概率丢失并清空`config/Console/ermissionService.yml`的内容，对开发很不友好）
> 
> 如果无法复现的话，那建议等v2.11正式版出来以后，看是不是仍然有这个bug

感谢帮助，不过，**我又发现一个问题**
在`ms open`之后，不会出现提示符，也无法接受任何输入，输`ms disconnect`提示符就出现了，再重新`ms connect`，依然无法接受任何输入

**Comment by asforest** [comment]
提示符是指linux shell 程序的提示符吗？类似于这种吗

![image](https://user-images.githubusercontent.com/28993050/158024232-4923c5de-7054-403f-94ab-453ab34bf9a3.png)

因为提示符后面没有跟上换行符，所以这段文字会被缓存，不会立即输出出来，你随便输个什么指令，比如time之类的，提示符和命令的执行结果应该就能一起显示出来了

---

另外无法接受任何输可以仔细描述一下吗

**Comment by DreamOneX** [comment]
> 提示符是指linux shell 程序的提示符吗？类似于这种吗
> 
> ![image](https://user-images.githubusercontent.com/28993050/158024232-4923c5de-7054-403f-94ab-453ab34bf9a3.png)
> 
> 因为提示符后面没有跟上换行符，所以这段文字会被缓存，不会立即输出出来，你随便输个什么指令，比如time之类的，提示符和命令的执行结果应该就能一起显示出来了
> 
> ---
> 
> 另外无法接受任何输可以仔细描述一下吗

![-59d374adc02302de.jpg](https://user-images.githubusercontent.com/83908457/158024456-ef0c4d1a-7835-4ec2-a82d-d21635c3bf11.jpg)

如图

**Comment by asforest** [comment]
可能还是权限的问题导致的（发送的消息也是有权限检测的，但这个检测和使用指令的检测用的不是同一个mirai-console 的API，按理来说两者行为应该一致才对。要么就是mirai-console在2.11版本里对这些东西进行了什么大改（虽然可能性很低啦）），我这边也是2.11.0-M1但是却能正常工作，我的系统是 WSL2 Ubuntu `Linux DESKTOP-QT68Q8J 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

![image](https://user-images.githubusercontent.com/28993050/158024627-c5ef2ead-2b12-4302-bdda-5673aef710b4.png)

---

如果可以的话，建议退回mirai-console到2.10版本看是否仍有这个问题
