### ISSUE TITLE
/ms kill 无效？

### ISSUE THREAD

**Issue by siltal** [asforest/MShell#7]
![SAVI@(I9A$}9UI$}P{IKK0H](https://user-images.githubusercontent.com/35952127/231100965-3206424f-7682-4227-8dbf-9f0778d9aca8.png)

**Comment by asforest** [comment]
有时候kill确实结束不了进程，可能是一个叫pty4j的库的问题

从代码层面暂时还解决不了这个问题，如果发生卡死的情况，只能用断开会话中的那个数字，也就是pid。打开系统shell，用 kill 命令来强制结束这个进程

**Comment by asforest** [comment]
你可以试试把预设中的pty模式关闭试试能不能正常退出

**Comment by siltal** [comment]
pty模式关闭, 使用 /ms kill 确实不回复了，但是无法继续执行命令也关不掉

**Comment by asforest** [comment]
无法执行命令是指插件卡死了吗？/ms help能执行吗

**Comment by siltal** [comment]
能的

**Comment by asforest** [comment]
在任务管理器里能看到那个进程还在运行吗

**Comment by asforest** [comment]
这个结束进程的机制我从代码里无法控制，具体行为完全依靠JVM实现。

就尽量让程序正常退出会比较好一点。或者在另一个会话里手动调用系统命令停止掉这个进程的pid。目前没有特别有效的方法能解决

**Comment by siltal** [comment]
加一个强停命令如何比如 forcestop="kill -9 $pid"

**Comment by asforest** [comment]
可以的

**Comment by asforest** [comment]
试试这个开发版的 /ms forcekill <pid> 指令，如果没问题我就发release了 [MShell-0.0.0.mirai2.jar.zip](https://github.com/asforest/MShell/files/11206066/MShell-0.0.0.mirai2.jar.zip) （文件名需要把后面的zip去掉）

**Comment by asforest** [comment]
超时未回复
